# Generated by Django 4.1 on 2023-11-02 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ip_cou",
        ),
    ]
