# Generated by Django 4.1 on 2023-10-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=128, unique=True)),
                ("ihl", models.CharField(max_length=128)),
                ("tos", models.CharField(max_length=256)),
                ("len", models.CharField(max_length=256)),
                ("uid", models.CharField(max_length=128, unique=True)),
                ("frag", models.CharField(max_length=256, unique=True)),
                ("ttl", models.CharField(max_length=128)),
                ("proto", models.CharField(max_length=256)),
                ("chksum", models.CharField(max_length=128)),
                ("src", models.CharField(max_length=64, unique=True)),
                ("dst", models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
