# Generated by Django 4.1 on 2023-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dst",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="src",
            field=models.CharField(max_length=64),
        ),
    ]
