# Generated by Django 4.1 on 2023-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_user_dst_alter_user_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="frag",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="version",
            field=models.CharField(max_length=128),
        ),
    ]
